### ISSUE TITLE
[FEATURE] Vehicle selection panel improvements

### ISSUE THREAD

**Issue by ZzZombo** [klyte45/ImprovedTransportManager#11]
**Is your feature request related to a problem? Please describe.**
Currently you can't undo any changes done in this panel. Also, when you only want to disable a few models your only way to do so is manually which sucks when it's a long list.

**Describe the solution you'd like**
This panel should have a button to reset to default and invert the selection.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by klyte45** [comment]
These changes are almost ready to be released this week in version 0.2 (aka beta 2), along with vehicle model and depot groups which will improve the UX once will be able to share a common vehicle/depot selection through many lines.
 
![image](https://user-images.githubusercontent.com/11671356/217029410-098a38ba-0aeb-4fef-8407-da3549f43014.png)

**Comment by klyte45** [comment]
The version 0.2 was finally released. Please take a look there!
