### ISSUE TITLE
Vehicles not being added to new lines

### ISSUE THREAD

**Issue by kiran-evans** [klyte45/ImprovedTransportManager#12]
**Describe the bug**
Vehicles not spawning on new lines.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new line
2. Vehicles not spawning on the line

I initially thought this was just affecting ferries but I tried it on other transports and it's all of them.

**Comment by klyte45** [comment]
Please attach logs from session that this happened to I have conditions to check this. Use the bug report template for this, there are instructions about how to get it.

**Comment by kiran-evans** [comment]
I found out that the reason this was happening was because I had "Use budget control" enabled in the mod settings.
