### ISSUE TITLE
[FEATURE] Custom Vehicle Assets

### ISSUE THREAD

**Issue by JerryJJC** [klyte45/ImprovedTransportManager#15]
Can't add custom vehicle assets, wanna add a feature for it.

**Comment by kiran-evans** [comment]
> Can't add custom vehicle assets, wanna add a feature for it.

What do you mean by custom vehicle assets? You can change the vehicles used on the lines.

**Comment by klyte45** [comment]
Please explain better your issue for reopening this issue
