### ISSUE TITLE
Buses will not spawn

### ISSUE THREAD

**Issue by Der-Orso** [klyte45/ImprovedTransportManager#3]
I cannot get any buses to spawn.

In my city, I already had about 50 bus lines setup with TLM.

Many lines use downloaded buses; mostly hybrid or biofuel, but some electric (not trolly buses). They all were spawned from a bio-fuel bus depot. I also have some vanilla bio-fuel buses.

All of the bus-types I used in TLM are also listed in ITM, plus the new buses from the Roads & Vehicles free DLC.

All of the bus lines had buses running on them before In switched from TLM to ITM, but none of the lines had a depot defined nor a bus type.

Since switching, to ITM, many of the lines have lost all of their buses.

Starting with lines with no running buses, I started defining the home depot and the bus-type, and set the budget to the number of buses I required. Then I waited to see if buses would spawn, but none ever did.

Some lines still have buses running, but but I cannot see why they are different, nor can I add buses to those lines.

I originally had 3 biofuel depots, each of which had more that 50 buses originating from them, so I added a fourth depot 
I've gone through and assigned a bus-type and a depot--I even built a fourth depot and divided up which line uses which depot so that no depot is over-burdened.

I also have metro and train lines running. I setup one of the metro lines that it has it's attached depot (I have MOM) and upped the number of trains from the default 4 to 8 or ten, any they all spawned without issue. 

I did the same with one of the train lines, also no issues.

I have a whole lot of mods installed, but I am loath to uninstall them all and start re-added them one by one to see if there is a specific one or maybe combination causing the issue, without first asking, because debugging like that will take hours and days.

If you have any tips in advance, please advise.

Regards
DerOrso

**Comment by StarrWulfe** [comment]
I had a similar issue with one tram depot out of three I had in my build-- trams would not spawn and kept timing out. I fixed the issue by 

1. bulldozing it and plopping a new one.
2. I then created a test line using the new depot and it worked. 
3. Lastly, I decommissioned the test line and reassigned the proper lines to the depot and they began spawning.

There may be a database issue happening behind the scenes is my best guess here...

**Comment by Der-Orso** [comment]
That sounds kind of similar to a different issue I was having. I had two unique factories, which each required plastics. Both were on the forestry industrial zone, because they also needed paper and timber, which they could source locally without long road trips or cargo trains.
I've been using Transfer Mager CE. So I played around with the setting for the Oil industries warehouse for plastics--where all the production goes, before distribution or export--plus the local depot where the plastics are warehoused before going to the unique factories, and I finally got one factory receive plastics and work again, but the other was impossible. I bulldozed it and then plopped a new identical one, set it up exactly as the previous one in Transfer Manager CE and boom it worked.
So the issue has nothing to do with the setting themselves, bc I've proven that they work. The issue is an internal bug, which is probably preventing requests for resources from reaching the distributer.
In my case with the factory, I could see the requests for plastics going out every few seconds, but non ever arriving at the local warehouse.
Depots seem to use the same mechanism as factories, but there is no way to monitor a bus line, if it is making requests for buses, and I cannot see any in the depot, which may not be getting any, because the database is not connecting the line to the depot.
I'm also getting a Harmoney error, at game start, which complains about path something or other, but cannot name the mod causing it, and I haven't had time to find out if its ITM or something else.

**Comment by Der-Orso** [comment]
So, after hours and hours of bashing at this issue from all sides, I found a tip that Roads & Vehicles f*cked up Biofuel depots so that apparently only vanilla biofuel buses can spwan there (apparently, but I've not satisfactorily confirmed it).

In my city I have only vanilla biofuel and workshop biofuel and hybrid buses, and the hybrid buses are noted to actually be biofuel buses bc CS doesn't actually have or support electric or battery buses.

The short of it, someone suggested that a regular bus depot is required to spawn non-vanilla biofuel buses, and I can confirm, after adding a single non-biofuel bus depot, workshop biofuel buses, which previously spawned from biofuel depots, starred spawning from the non-biofuel depot... and then eventually from the biofuel depots.

It's still FUBARed and erratic. but it seems that issue has nothing to do with ITM, as with the non-biofuel depot and ITM, I can get buses to spawn.

**Comment by Der-Orso** [comment]
Okay, I've done my last test.
These are the workshop buses I have:
CommunityBus v2 [https://steamcommunity.com/sharedfiles/filedetails/?id=629401365](url)
[BIO BUS] 2014 Van Hool A300K Hybrid [https://steamcommunity.com/sharedfiles/filedetails/?id=1332099161](url)
[BIO BUS] 2019 Gillig BRT Hybrid 29' Bus contains also [BIO BUS] 2019 Gillig ALT BRT Hybrid 29' Bus (I can't tell the difference) [https://steamcommunity.com/sharedfiles/filedetails/?id=1586792933](url)
[BIO BUS] 2018 New Flyer XE40 [https://steamcommunity.com/sharedfiles/filedetails/?id=1207778758](url)
[BIO BUS] 2018 New Flyer [XE60](https://steamcommunity.com/sharedfiles/filedetails/?id=1207778969)
D3S Volvo 7900 Electric Hybrid [https://steamcommunity.com/sharedfiles/filedetails/?id=1551102541](url)
D3S Volvo 7900 Hybrid Articulated '2011 [https://steamcommunity.com/sharedfiles/filedetails/?id=475409805](url)
Before Roads & Vehicles DLC, using IPT2 and TLM14.4 they always spawned from Biofuel Bus Depots without issue.

The map I used for tests and experiments was saved from before the R&V DLC, and used all of the above workshop buses in at least on line. The map had 3 Biofuel Bus Depots on it, but no others.

After R&V I had a lot of issues getting all mods to work properly--mostly having to wait for updates. I tried using ITM during this time, but always had issues trying to get buses to spawn.

After having fixed all my mods issues, I tried to pick-up where I left off on my current map using ITM instead of TLM. 

I discovered that with ITM, after loading the map for the first time, for all lines, all bus types were unselected (which in game terms means, the game picks a random vehicle if one is required), and all assigned depots were unselected (which in game terms means, the game picks which ever one it wants, generally the closest to the line), from what I could see.

If a line had buses already running on it, they remained in service, but I could not get any buses to be added to the line, nor could I get bus type to change, if I selected a new in the line details page.

Eventually I read that only vanilla biofuel buses could spawn on a biofuel depot, so I added a nromal vanilla depot.

I reloaded my map from before R&V, added a regular vanilla depot and observed. nearly all the buses on all the lines canceled their services and started returning to depots. I noted that all the workshop buses were returning to the Biofuel depots, and none to the newly added vanilla bus depot. But I could only get the workshop buses to spawn if a vanilla non-biofuel depot were also on the map. Sometimes I had to add the vanilla depot to the list of depots for the line to get new buses to spawn, but not always. It was at best erratic in behavior.

====

My last test was to un-install all TM mods, but leave all the workshop buses. I loaded my last map-save and checked the bus lines. ALL bus lines had the vanilla "bus" type assigned to them. Only one line had no buses in service, but I believe that was an issue I had carried into the situation unwittingly.
I knew from pervious tests with ITM or TLM installed, since on my map I had no vanilla diesel buses running, if I simply un-paused the game, immediately all buses were taken out of service and proceeded to return to depot. If I didn't add a vanilla diesel bus depot, none of the workshop buses could spawn.. If I added a vanilla depot,, and random buses were spawned to populate the bus lines.

My last test was to have no TM installed, load the map and assign all the bus lines with one of the workshop bus types, nearly always the type already being used on the line (by opening the detail display and clicking on a bus on the line diagram to locate that bus, I could determine which bus type was being used on which line, so I selected the same type nearly always (as an experiment I picked a different bus on one line - the buses already in service on that line immediately retured to depot and new ones of the selected type were spawned).

After adjusting all the bus lines so that each had a workshop bus assigned, I un-paused and observed. All the buses ran normally. The bus lines with new types assigned got new buses, and everything ran as was to be expected, with the exception of the D3S Volvo 7900 Hybrid Articulated '2011 which I could not get to spawn, although the D3S Volvo 7900 Electric Hybrid  was spawned and running.

This was all without ITM installed, so it seems that there is some issue with ITM and these workshop buses, at least when lines and buses are already in place on the map. I haven't tried to start a new map, to see what happens there.

**Comment by klyte45** [comment]
Seems to be an very old issue that potentially was solved in r9. I did checked recently with these assets and seems to be ok.

If it still being an issue, please create a new issue in the new issue template format.
