### ISSUE TITLE
[BUG] Vehicles return to depot at save load.

### ISSUE THREAD

**Issue by sergjack2015** [klyte45/ImprovedTransportManager#7]
**Describe the bug**
Upon the savegame loading, some vehicles on PT lines return to depot even tho the number of vehicles on the line hasnt changed and they have passangers in them.

**To Reproduce**
1. make PT line
2. reload save
3. some vehicles on the line should return to depot

**Game Logs**
[output_log.txt](https://github.com/klyte45/ImprovedTransportManager/files/10300102/output_log.txt)
[ITM.log.txt](https://github.com/klyte45/ImprovedTransportManager/files/10300099/ITM.log.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/80580018/209471408-6f5e28a7-28e2-40b1-b231-1107e15771dd.png)

**Additional context**
ITM explicitly says that behaviour like this will not happen.

**Comment by klyte45** [comment]
I'm betting it's an incompatibility with TransferManagerCE, once it changes the vanilla Transfer Manager that's used by ITM to control this setting

I'll get deep in that mod to check, but you are welcome to try disabling it to test if this is the issue

**Comment by klyte45** [comment]
Well, tested this mod here and no issues found. I will need more details (like which line this bus was from as example) 

As well, the log sent is invalid: there are no city load logs at ITM.log.txt. I will need a valid log after loaded a city with this issue, and before the game get rebooted

**Comment by heckyps** [comment]
I'm having this exact same issue. The thing is that even creating a new bus line, no busses are spawned so the lines are becoming empty from load to load.
I was using TLM without issues.

<img width="1456" alt="cities " src="https://user-images.githubusercontent.com/124462387/216784597-1c19f2ee-668f-4d1f-af87-2b74fac02de0.png">

[ITM.log.txt](https://github.com/klyte45/ImprovedTransportManager/files/10609405/ITM.log.txt)
[output_log.txt](https://github.com/klyte45/ImprovedTransportManager/files/10609414/output_log.txt)

**Comment by klyte45** [comment]
@heckups seems that you haven't loaded the game with debug mode on. I need to require it to check if the saved data is loading well.

Just clarifying, it happened when doing the migration from TLM to ITM?

**Comment by heckyps** [comment]
You're right, I forgot to load the game with debug mode on. Here the correct log: 
[output_log.txt](https://github.com/klyte45/ImprovedTransportManager/files/10611867/output_log.txt)

As fas as I noticed, the issue started when I changed the mod to this one. FYI going back to TLM doesn't fix it.

**Comment by klyte45** [comment]
It's missing the ITM.log.txt 

Anyway, this behavior is kind of expected in a savegame that was done with TLM then loaded with ITM. You will need to reconfigure it all, and probably there will have "debris" from TLM in behavior of the savegame for some frames. ITM only will take place on all settings after being re-configured and saved past at least 1 week in game pace (or 30min in Real Time at default speed)
